use crate::service::{
    ErrorControl, NotifyAccess, Readiness, RestartPolicy, ServiceCheck, ServiceDefinition,
    ServiceEnvironmentVariable, ServiceSecurityDescriptor, ServiceTrigger, ServiceType,
};

use super::super::ServiceRegistryDecodeError;

const DEFAULT_IDENTITY: &str = "LocalService";

pub(super) struct DefinitionBuilder {
    pub(super) name: String,
    pub(super) image_path: Option<String>,
    pub(super) arguments: Vec<String>,
    pub(super) service_type: ServiceType,
    pub(super) triggers: Vec<ServiceTrigger>,
    pub(super) disabled: bool,
    pub(super) safe_mode: bool,
    pub(super) identity: String,
    pub(super) required_privileges: Vec<String>,
    pub(super) requires: Vec<String>,
    pub(super) wants: Vec<String>,
    pub(super) binds_to: Vec<String>,
    pub(super) conflicts: Vec<String>,
    pub(super) on_failure: Option<String>,
    pub(super) readiness: Readiness,
    pub(super) notify_access: NotifyAccess,
    pub(super) remain_after_exit: bool,
    pub(super) success_exit_codes: Vec<i32>,
    pub(super) exec_start_pre: Vec<String>,
    pub(super) exec_start_post: Vec<String>,
    pub(super) hook_identity: Option<String>,
    pub(super) exec_reload: Option<String>,
    pub(super) pre_start_check_timeout_secs: u64,
    pub(super) start_timeout_secs: u64,
    pub(super) stop_timeout_secs: u64,
    pub(super) watchdog_timeout_secs: u64,
    pub(super) health_check: Option<String>,
    pub(super) health_check_interval_secs: u64,
    pub(super) health_check_timeout_secs: u64,
    pub(super) health_check_retries: u32,
    pub(super) fd_store_max: u32,
    pub(super) environment: Vec<ServiceEnvironmentVariable>,
    pub(super) working_directory: String,
    pub(super) limit_nofile: Option<u64>,
    pub(super) limit_core: Option<u64>,
    pub(super) conditions: Vec<ServiceCheck>,
    pub(super) asserts: Vec<ServiceCheck>,
    pub(super) display_name: Option<String>,
    pub(super) description: Option<String>,
    pub(super) restart_policy: RestartPolicy,
    pub(super) restart_max_retries: u32,
    pub(super) restart_window_secs: u64,
    pub(super) restart_delay_secs: u64,
    pub(super) error_control: ErrorControl,
    pub(super) service_security: ServiceSecurityDescriptor,
    pub(super) timer_persistent: bool,
    pub(super) timer_jitter_secs: u64,
}

impl DefinitionBuilder {
    pub(super) fn new(service_name: &str) -> Self {
        Self {
            name: service_name.to_string(),
            image_path: None,
            arguments: Vec::new(),
            service_type: ServiceType::Simple,
            triggers: Vec::new(),
            disabled: false,
            safe_mode: false,
            identity: DEFAULT_IDENTITY.to_string(),
            required_privileges: Vec::new(),
            requires: Vec::new(),
            wants: Vec::new(),
            binds_to: Vec::new(),
            conflicts: Vec::new(),
            on_failure: None,
            readiness: Readiness::Notify,
            notify_access: NotifyAccess::Main,
            remain_after_exit: false,
            success_exit_codes: Vec::new(),
            exec_start_pre: Vec::new(),
            exec_start_post: Vec::new(),
            hook_identity: None,
            exec_reload: None,
            pre_start_check_timeout_secs: ServiceDefinition::DEFAULT_PRE_START_CHECK_TIMEOUT_SECS,
            start_timeout_secs: ServiceDefinition::DEFAULT_START_TIMEOUT_SECS,
            stop_timeout_secs: ServiceDefinition::DEFAULT_STOP_TIMEOUT_SECS,
            watchdog_timeout_secs: ServiceDefinition::DEFAULT_WATCHDOG_TIMEOUT_SECS,
            health_check: None,
            health_check_interval_secs: ServiceDefinition::DEFAULT_HEALTH_CHECK_INTERVAL_SECS,
            health_check_timeout_secs: ServiceDefinition::DEFAULT_HEALTH_CHECK_TIMEOUT_SECS,
            health_check_retries: ServiceDefinition::DEFAULT_HEALTH_CHECK_RETRIES,
            fd_store_max: ServiceDefinition::DEFAULT_FD_STORE_MAX,
            environment: Vec::new(),
            working_directory: ServiceDefinition::DEFAULT_WORKING_DIRECTORY.to_string(),
            limit_nofile: None,
            limit_core: None,
            conditions: Vec::new(),
            asserts: Vec::new(),
            display_name: None,
            description: None,
            restart_policy: ServiceDefinition::DEFAULT_RESTART_POLICY,
            restart_max_retries: ServiceDefinition::DEFAULT_RESTART_MAX_RETRIES,
            restart_window_secs: ServiceDefinition::DEFAULT_RESTART_WINDOW_SECS,
            restart_delay_secs: ServiceDefinition::DEFAULT_RESTART_DELAY_SECS,
            error_control: ServiceDefinition::DEFAULT_ERROR_CONTROL,
            service_security: ServiceSecurityDescriptor::Default,
            timer_persistent: ServiceDefinition::DEFAULT_TIMER_PERSISTENT,
            timer_jitter_secs: ServiceDefinition::DEFAULT_TIMER_JITTER_SECS,
        }
    }

    pub(super) fn finish(mut self) -> Result<ServiceDefinition, ServiceRegistryDecodeError> {
        if self.error_control == ErrorControl::Critical {
            self.safe_mode = true;
        }
        Ok(ServiceDefinition {
            name: self.name,
            image_path: self
                .image_path
                .ok_or(ServiceRegistryDecodeError::MissingImagePath)?,
            arguments: self.arguments,
            service_type: self.service_type,
            triggers: self.triggers,
            disabled: self.disabled,
            safe_mode: self.safe_mode,
            identity: self.identity,
            required_privileges: self.required_privileges,
            requires: self.requires,
            wants: self.wants,
            binds_to: self.binds_to,
            conflicts: self.conflicts,
            on_failure: self.on_failure,
            readiness: self.readiness,
            notify_access: self.notify_access,
            remain_after_exit: self.remain_after_exit,
            success_exit_codes: self.success_exit_codes,
            exec_start_pre: self.exec_start_pre,
            exec_start_post: self.exec_start_post,
            hook_identity: self.hook_identity,
            exec_reload: self.exec_reload,
            pre_start_check_timeout_secs: self.pre_start_check_timeout_secs,
            start_timeout_secs: self.start_timeout_secs,
            stop_timeout_secs: self.stop_timeout_secs,
            watchdog_timeout_secs: self.watchdog_timeout_secs,
            health_check: self.health_check,
            health_check_interval_secs: self.health_check_interval_secs,
            health_check_timeout_secs: self.health_check_timeout_secs,
            health_check_retries: self.health_check_retries,
            fd_store_max: self.fd_store_max,
            environment: self.environment,
            working_directory: self.working_directory,
            limit_nofile: self.limit_nofile,
            limit_core: self.limit_core,
            conditions: self.conditions,
            asserts: self.asserts,
            display_name: self.display_name,
            description: self.description,
            restart_policy: self.restart_policy,
            restart_max_retries: self.restart_max_retries,
            restart_window_secs: self.restart_window_secs,
            restart_delay_secs: self.restart_delay_secs,
            error_control: self.error_control,
            service_security: self.service_security,
            timer_persistent: self.timer_persistent,
            timer_jitter_secs: self.timer_jitter_secs,
        })
    }
}
