/* @generated by cbindgen from the Rust source - do not edit. */

#ifndef PEINIT_ABI_GENERATED_H
#define PEINIT_ABI_GENERATED_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#define PEINIT_ERR_INTERNAL -6

#define PEINIT_ERR_INVALID_ARGUMENT -1

#define PEINIT_ERR_IO -2

#define PEINIT_ERR_NO_MEMORY -5

#define PEINIT_ERR_PROTOCOL -3

#define PEINIT_ERR_UNAVAILABLE -4

#define PEINIT_OK 0

#define PEINIT_SHUTDOWN_HALT 2

#define PEINIT_SHUTDOWN_POWEROFF 0

#define PEINIT_SHUTDOWN_REBOOT 1

typedef void peinit_client_t;

typedef void peinit_error_t;

typedef void peinit_response_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

unsigned int peinit_abi_version(void);

int peinit_client_connect_default(peinit_client_t **out, peinit_error_t **error_out);

int peinit_client_connect_path(const char *path, peinit_client_t **out, peinit_error_t **error_out);

void peinit_client_free(peinit_client_t *client);

int peinit_control_raw_json(peinit_client_t *client,
                            const char *request_json,
                            peinit_response_t **response_out,
                            peinit_error_t **error_out);

const char *peinit_default_control_socket_path(void);

int peinit_error_code(const peinit_error_t *error);

void peinit_error_free(peinit_error_t *error);

const char *peinit_error_message(const peinit_error_t *error);

const char *peinit_library_version(void);

int peinit_notify_extend_timeout_usec(unsigned long long usec, peinit_error_t **error_out);

int peinit_notify_ready(peinit_error_t **error_out);

int peinit_notify_reloading(peinit_error_t **error_out);

int peinit_notify_send(const char *message, peinit_error_t **error_out);

int peinit_notify_send_to(const char *socket_path, const char *message, peinit_error_t **error_out);

int peinit_notify_status(const char *status, peinit_error_t **error_out);

int peinit_notify_stopping(peinit_error_t **error_out);

int peinit_notify_watchdog(peinit_error_t **error_out);

int peinit_notify_watchdog_usec(unsigned long long usec, peinit_error_t **error_out);

int peinit_operation_status(peinit_client_t *client,
                            const char *operation_id,
                            peinit_response_t **response_out,
                            peinit_error_t **error_out);

int peinit_reload_config(peinit_client_t *client,
                         peinit_response_t **response_out,
                         peinit_error_t **error_out);

const char *peinit_response_error_code(const peinit_response_t *response);

const char *peinit_response_error_message(const peinit_response_t *response);

void peinit_response_free(peinit_response_t *response);

int peinit_response_is_ok(const peinit_response_t *response);

const char *peinit_response_json(const peinit_response_t *response);

const char *peinit_response_status(const peinit_response_t *response);

int peinit_service_list(peinit_client_t *client,
                        peinit_response_t **response_out,
                        peinit_error_t **error_out);

int peinit_service_reload(peinit_client_t *client,
                          const char *service,
                          bool wait,
                          peinit_response_t **response_out,
                          peinit_error_t **error_out);

int peinit_service_reset(peinit_client_t *client,
                         const char *service,
                         peinit_response_t **response_out,
                         peinit_error_t **error_out);

int peinit_service_restart(peinit_client_t *client,
                           const char *service,
                           bool wait,
                           peinit_response_t **response_out,
                           peinit_error_t **error_out);

int peinit_service_start(peinit_client_t *client,
                         const char *service,
                         bool wait,
                         peinit_response_t **response_out,
                         peinit_error_t **error_out);

int peinit_service_status(peinit_client_t *client,
                          const char *service,
                          peinit_response_t **response_out,
                          peinit_error_t **error_out);

int peinit_service_stop(peinit_client_t *client,
                        const char *service,
                        bool wait,
                        peinit_response_t **response_out,
                        peinit_error_t **error_out);

const char *peinit_status_name(int status);

void peinit_string_free(char *value);

int peinit_system_shutdown(peinit_client_t *client,
                           int shutdown_kind,
                           peinit_response_t **response_out,
                           peinit_error_t **error_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PEINIT_ABI_GENERATED_H */
